services:
  - type: web
    name: number-guess-game
    env: docker
    plan: free
    region: oregon
    branch: main
    autoDeploy: true
    envVars:
      - key: EMAIL_USERNAME
        sync: false
      - key: EMAIL_PASSWORD
        sync: false
